### ISSUE TITLE
PhpStorm - Wrong Object and $this-> Color

### ISSUE THREAD

**Issue by Slyrc** [samdark/intellij-visual-studio-code-dark-plus#21]
### What the issue is?

When creating a new Object in php, or using $this->, the wrong colours are applied. See screenshots.

### Screenshots

PhpStorm Screenshot:
![04B4191E-527A-4E5B-ABB1-3DD00117DDC1](https://user-images.githubusercontent.com/62191325/76692339-5d318080-6655-11ea-86b1-7ad71316aab2.png)

VS Code:
![15C3714D-0B52-432B-A0E5-1D578CB7ED09](https://user-images.githubusercontent.com/62191325/76692346-7b977c00-6655-11ea-933d-70d54ed0c48d.png)

Expected result: PhpStorm should display the same syntax highlighting as VS Code.

### How would you fix it?

Apply the right colours. Not sure how this would work here. I would copy the Color codes and add them to the plugin?

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 1.9
| IDE and version  | 2019.3.3 // PS-193.6494.47, built on February 12, 2020
| Operating system | Mac OS 10.14.6

**Comment by samdark** [comment]
See https://github.com/samdark/intellij-visual-studio-code-dark-plus/issues/18#issuecomment-593072992

**Comment by amstiel** [comment]
I don't see this as bug. It's lack of IDEA code highlighting. You can't set color for `$this` in PHP, because IDEA see this as common variable. Like you can't highlight `import`/`export` keywords in JavaScript. IDEA don't see difference between `import` and other keywords.

But you can use something like [Custom Syntax Highligher](https://github.com/mallowigi/Custom-Syntax-Highlighter) plugin, or my WIP [fork](https://github.com/amstiel/Custom-Syntax-Highlighter/releases). This plugin allows you to set color for specific part of code, like `$this` in PHP. I'm just adding functionality for improved PHP highlighting.

Or you can use [Material Theme UI](https://plugins.jetbrains.com/plugin/8006-material-theme-ui). It has built-in support for PHP improved highlighting. Because Custom Syntax Highlighter is just a part of it. And my implementation of PHP improved highlighting part of it too.

P.S. I'm not working with PHP that much as with JavaScript. So it will be very helpful if you find more specific keywords, which have improved highlight in VSCode.

**Comment by amstiel** [comment]
So you can get something like this:

VSCode
![image](https://user-images.githubusercontent.com/9428948/85406365-0b2dbe80-b5a5-11ea-9eea-b7149c51af3e.png)

PhpStorm
![image](https://user-images.githubusercontent.com/9428948/85406961-e554e980-b5a5-11ea-893e-a9895bb22d6e.png)

Yeah, I know, `return` and some other keywords still WIP 😄

**Comment by amstiel** [comment]
Just in case you want try my fork of Custom Syntax Highlighter, you should get latest release from GitHub repo releases tab and install it manually:

![image](https://user-images.githubusercontent.com/9428948/85407889-25689c00-b5a7-11ea-80f6-86315fa77397.png)

**Comment by samdark** [comment]
I think it is a good idea to report all these extra tokens we want to highlight to JetBrains issue tracker.

**Comment by amstiel** [comment]
Yeah, of course. There is a [issue](https://youtrack.jetbrains.com/issue/IDEABKL-5473) in JetBrains tracker with 110 upvotes. Custom Syntax Highlighter is just a temporary solution, proof of concept.

**Comment by samdark** [comment]
111.

**Comment by samdark** [comment]
Seems it can be adjusted in recent PhpStorm versions.
