### ISSUE TITLE
Java (and Kotlin) colour scheme still use settings from Darcula theme

### ISSUE THREAD

**Issue by GauthierPLM** [samdark/intellij-visual-studio-code-dark-plus#3]
Not all colour scheme properties are defined in Java or marked as inherited from Language Defaults. This cause a part of the code to look weird because Darcula colors are still used.

Preview from Colour Scheme settings:

<img width="571" alt="Capture d’écran 2019-07-05 à 14 57 24" src="https://user-images.githubusercontent.com/2579741/60701058-49197900-9f35-11e9-9a35-0f6884a2ca5b.png">

This also impact Kotlin as Kotlin settings are mostly inherited from Java:

<img width="890" alt="Capture d’écran 2019-07-05 à 14 57 40" src="https://user-images.githubusercontent.com/2579741/60701073-546ca480-9f35-11e9-9ceb-f17645c80030.png">

Note that I use IntelliJ IDEA 2019.2.

**Comment by samdark** [comment]
Noted. I'll try to figure it out. If you want to help you may define colors, export color schema and attach it to the issue... or make a pull request by merging color schema with https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/resources/visual_studio_code_dark_plus.xml. Note that not every color defined there is exported by IDE itself. Scrollbar colors are not but these should be kept.

**Comment by samdark** [comment]
Going to handle it.

**Comment by samdark** [comment]
Done. Will schedule release. Thanks for reporting!

**Comment by Gameghostify** [comment]
This happens with JavaScript code as well, unfortunately

![image](https://user-images.githubusercontent.com/33099493/66208696-0727dc80-e6b6-11e9-9603-2db73762e2ae.png)

Is there any quick fix to this? I'd open a PR but I don't know that much about IntelliJ theming

**Comment by samdark** [comment]
@Gameghostify it is better to report as separate issue since discussions on closed issues are often lost :(

As for theming, it is easy. Open your IDE. Go to "Color Scheme", select "Visual Studio Code Dark Plus" then JavaScript and adjust colors. When done press gear icon:

![image](https://user-images.githubusercontent.com/47294/66211533-f7fc5b00-e6c4-11e9-8423-92f64af641bf.png)

Choose "Export" and select `.icls`. That would give you a file to merge with https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/resources/visual_studio_code_dark_plus.xml. It is not exporting some values such as `ScrollBar` so these should be left as is.
